/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as TestRouteImport } from './app/test'
import { Route as TermsAndConditionsRouteImport } from './app/terms-and-conditions'
import { Route as PrivacyPolicyRouteImport } from './app/privacy-policy'
import { Route as OurGalleryRouteImport } from './app/our-gallery'
import { Route as OurClientsRouteImport } from './app/our-clients'
import { Route as AboutRouteImport } from './app/about'
import { Route as CoursesRouteImport } from './app/Courses'
import { Route as ContactRouteImport } from './app/Contact'
import { Route as CalendarRouteImport } from './app/Calendar'
import { Route as AccreditationRouteImport } from './app/Accreditation'
import { Route as IndexRouteImport } from './app/index'
import { Route as CourseSlugRouteImport } from './app/course.$slug'
import { Route as CategorySlugRouteImport } from './app/category.$slug'
import { Route as CourseRegistrationSlugRegisterRouteImport } from './app/course-registration.$slug.register'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const OurGalleryRoute = OurGalleryRouteImport.update({
  id: '/our-gallery',
  path: '/our-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const OurClientsRoute = OurClientsRouteImport.update({
  id: '/our-clients',
  path: '/our-clients',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/Courses',
  path: '/Courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/Contact',
  path: '/Contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/Calendar',
  path: '/Calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AccreditationRoute = AccreditationRouteImport.update({
  id: '/Accreditation',
  path: '/Accreditation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseSlugRoute = CourseSlugRouteImport.update({
  id: '/course/$slug',
  path: '/course/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseRegistrationSlugRegisterRoute =
  CourseRegistrationSlugRegisterRouteImport.update({
    id: '/course-registration/$slug/register',
    path: '/course-registration/$slug/register',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Accreditation': typeof AccreditationRoute
  '/Calendar': typeof CalendarRoute
  '/Contact': typeof ContactRoute
  '/Courses': typeof CoursesRoute
  '/about': typeof AboutRoute
  '/our-clients': typeof OurClientsRoute
  '/our-gallery': typeof OurGalleryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/test': typeof TestRoute
  '/category/$slug': typeof CategorySlugRoute
  '/course/$slug': typeof CourseSlugRoute
  '/course-registration/$slug/register': typeof CourseRegistrationSlugRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Accreditation': typeof AccreditationRoute
  '/Calendar': typeof CalendarRoute
  '/Contact': typeof ContactRoute
  '/Courses': typeof CoursesRoute
  '/about': typeof AboutRoute
  '/our-clients': typeof OurClientsRoute
  '/our-gallery': typeof OurGalleryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/test': typeof TestRoute
  '/category/$slug': typeof CategorySlugRoute
  '/course/$slug': typeof CourseSlugRoute
  '/course-registration/$slug/register': typeof CourseRegistrationSlugRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Accreditation': typeof AccreditationRoute
  '/Calendar': typeof CalendarRoute
  '/Contact': typeof ContactRoute
  '/Courses': typeof CoursesRoute
  '/about': typeof AboutRoute
  '/our-clients': typeof OurClientsRoute
  '/our-gallery': typeof OurGalleryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/test': typeof TestRoute
  '/category/$slug': typeof CategorySlugRoute
  '/course/$slug': typeof CourseSlugRoute
  '/course-registration/$slug/register': typeof CourseRegistrationSlugRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Accreditation'
    | '/Calendar'
    | '/Contact'
    | '/Courses'
    | '/about'
    | '/our-clients'
    | '/our-gallery'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/test'
    | '/category/$slug'
    | '/course/$slug'
    | '/course-registration/$slug/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Accreditation'
    | '/Calendar'
    | '/Contact'
    | '/Courses'
    | '/about'
    | '/our-clients'
    | '/our-gallery'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/test'
    | '/category/$slug'
    | '/course/$slug'
    | '/course-registration/$slug/register'
  id:
    | '__root__'
    | '/'
    | '/Accreditation'
    | '/Calendar'
    | '/Contact'
    | '/Courses'
    | '/about'
    | '/our-clients'
    | '/our-gallery'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/test'
    | '/category/$slug'
    | '/course/$slug'
    | '/course-registration/$slug/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccreditationRoute: typeof AccreditationRoute
  CalendarRoute: typeof CalendarRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  AboutRoute: typeof AboutRoute
  OurClientsRoute: typeof OurClientsRoute
  OurGalleryRoute: typeof OurGalleryRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  TestRoute: typeof TestRoute
  CategorySlugRoute: typeof CategorySlugRoute
  CourseSlugRoute: typeof CourseSlugRoute
  CourseRegistrationSlugRegisterRoute: typeof CourseRegistrationSlugRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-gallery': {
      id: '/our-gallery'
      path: '/our-gallery'
      fullPath: '/our-gallery'
      preLoaderRoute: typeof OurGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-clients': {
      id: '/our-clients'
      path: '/our-clients'
      fullPath: '/our-clients'
      preLoaderRoute: typeof OurClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Courses': {
      id: '/Courses'
      path: '/Courses'
      fullPath: '/Courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Contact': {
      id: '/Contact'
      path: '/Contact'
      fullPath: '/Contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Calendar': {
      id: '/Calendar'
      path: '/Calendar'
      fullPath: '/Calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Accreditation': {
      id: '/Accreditation'
      path: '/Accreditation'
      fullPath: '/Accreditation'
      preLoaderRoute: typeof AccreditationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$slug': {
      id: '/course/$slug'
      path: '/course/$slug'
      fullPath: '/course/$slug'
      preLoaderRoute: typeof CourseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course-registration/$slug/register': {
      id: '/course-registration/$slug/register'
      path: '/course-registration/$slug/register'
      fullPath: '/course-registration/$slug/register'
      preLoaderRoute: typeof CourseRegistrationSlugRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccreditationRoute: AccreditationRoute,
  CalendarRoute: CalendarRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  AboutRoute: AboutRoute,
  OurClientsRoute: OurClientsRoute,
  OurGalleryRoute: OurGalleryRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  TestRoute: TestRoute,
  CategorySlugRoute: CategorySlugRoute,
  CourseSlugRoute: CourseSlugRoute,
  CourseRegistrationSlugRegisterRoute: CourseRegistrationSlugRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
